### ISSUE TITLE
generated crd code fails to compile

### ISSUE THREAD

**Issue by capacman** [coralogix/zio-k8s#129]
Hi,
I try to generate code for below crd. 
https://raw.githubusercontent.com/fluxcd/helm-operator/1.2.0/deploy/crds.yaml
Since it is v1beta first i submit it with "kubectl apply -f" then use "kubectl get crd helmreleases.helm.fluxcd.io -o=yaml". Here is the generated code:
```scala
case class HelmRelease(
    status: com.coralogix.zio.k8s.client.model.Optional[HelmRelease.Status] =
      None,
    spec: HelmRelease.Spec,
    metadata: io.circe.Json,
    kind: com.coralogix.zio.k8s.client.model.Optional[String] = None,
    apiVersion: com.coralogix.zio.k8s.client.model.Optional[String] = None
)
```
```scala
implicit val k8sObject: K8sObject[HelmRelease] = new K8sObject[HelmRelease] {
    def metadata(obj: HelmRelease): Optional[ObjectMeta] = obj.metadata
    def mapMetadata(f: ObjectMeta => ObjectMeta)(
        obj: HelmRelease
    ): HelmRelease = obj.copy(metadata = obj.metadata.map(f))
  }
```
First issue is,generated metadata field is json. When i remove metadata from properties, it generates metadata as ObjectMeta but implicit val k8sObject declaration fails since ```def metadata ``` method return optional. Since i am new to kubernetes i dont know whether metadata field should be optional. If it is then crd is wrong. 

Another issue is if object declaration includes a field which can conflict with java Object. Since "wait" method is final in java below generated class fails to compile with 
```
```
[error] /home/capacman/programlama/scala/workspace/hydra/flux-helm/target/scala-2.13/src_managed/main/com/coralogix/zio/k8s/client/io/fluxcd/helm/definitions/helmrelease/v1/HelmRelease.scala:319:7: cannot override final member:
[error] final def wait(): Unit (defined in class Object)
[error]       wait: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None,
```scala
case class Rollback(
        enable: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None,
        wait: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None,
        force: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None,
        recreate: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None,
        maxRetries: com.coralogix.zio.k8s.client.model.Optional[Long] = None,
        disableHooks: com.coralogix.zio.k8s.client.model.Optional[Boolean] =
          None,
        timeout: com.coralogix.zio.k8s.client.model.Optional[Long] = None,
        retry: com.coralogix.zio.k8s.client.model.Optional[Boolean] = None
    )
```

**Comment by vigoo** [comment]
Thank you for reporting this! I believe the linked PR fixes all the issues. 
Will publish a new release as soon it's merged.

**Comment by capacman** [comment]
@vigoo thank you for your quick response and awesome library :)
