### ISSUE TITLE
DeserializationFailure on watchForever/getAll events

### ISSUE THREAD

**Issue by jupposessho** [coralogix/zio-k8s#144]
To reproduce:

- create a job with invalid image name
- use the service from com.coralogix.zio.k8s.client.events.v1.events.Events
- then call eventsService.getAll(Some(K8sNamespace.default)) or watchForever

Result: DeserializationFailure with  DownField(eventTime)

Cause: the eventTime is null for some events.

Request: GET https://kubernetes.docker.internal:6443/apis/events.k8s.io/v1/namespaces/default/events?limit=10

response item:

`{"metadata":{"name":"xxx-465r5-j76z8.166ba39bf354fa24","namespace":"default","selfLink":"/apis/events.k8s.io/v1/namespaces/default/events/xxx-465r5-j76z8.166ba39bf354fa24","uid":"2fd386cc-2cb9-4f61-aeb9-8d59946baa1b","resourceVersion":"1756627","creationTimestamp":"2021-03-12T15:59:41Z","managedFields":[{"manager":"kubelet","operation":"Update","apiVersion":"v1","time":"2021-03-12T16:34:48Z","fieldsType":"FieldsV1","fieldsV1":{"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{"f:apiVersion":{},"f:fieldPath":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:source":{"f:component":{},"f:host":{}},"f:type":{}}}]},"eventTime":null,"reason":"InspectFailed","regarding":{"kind":"Pod","namespace":"default","name":"xxx-465r5-j76z8","uid":"25ad2b4f-0395-4901-85b5-616d68df6575","apiVersion":"v1","resourceVersion":"1752753","fieldPath":"spec.containers{xxx-client-1}"},"note":"Failed to apply default image tag \"[invalid image]\": couldn't parse image reference \"[invalid image]\": invalid reference format","type":"Warning","deprecatedSource":{"component":"kubelet","host":"docker-desktop"},"deprecatedFirstTimestamp":"2021-03-12T15:59:41Z","deprecatedLastTimestamp":"2021-03-12T16:34:48Z","deprecatedCount":166}`

**Comment by vigoo** [comment]
Unfortunately the schema declares that field as required. I think we have to introduce an override list for property optionality in the code generator to solve this.

**Comment by vigoo** [comment]
Other similar case found by @iravid: `PodSpec#containers` was null
