### ISSUE TITLE
Support more operations for the Status subresource

### ISSUE THREAD

**Issue by vigoo** [coralogix/zio-k8s#21]
Currently `ResourceStatus` only contains `replaceStatus`. This interface should be extended with additional operations on the status subresource, 

The steps would be:
- Understand what is available by checking the swagger definition of the API and by experimenting with `kubectl`. Note that with `-v=6` verbosity it prints the performed HTTP requests.
- Implement the new operations in the generic `ResourceClientStatus` class and its namespaced/cluster wrappers and add the generic accessor functions
- Generate accessor functions in the code generator (`ClientModuleGenerator`)
- Add the new supported endpoints to `EndpointType` and `classifyResource` to guarantee that we only generate code for resources that support them.

Relevant documentation: https://kubernetes.io/docs/reference/using-api/api-concepts/

**Comment by jupposessho** [comment]
Working on this one.

**Comment by jupposessho** [comment]
Is this ready to close?

**Comment by vigoo** [comment]
Yes I think so!
