### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [coralogix/zio-k8s#257]
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by swoogles** [comment]
> @swoogles 
> I can start on upgrade to zio 2.0. Shall I go ahead?

That would be great! It looks like you will need to target ZIO `2.0.0-RC1` for now, as zio-nio and sttp haven't published releases for RC2 yet.
The differences between the RCs are minimal, so hopefully you can just bump the version in your build file once they are updated.

FYI I'm tracking library releases via
https://zio-ecosystem.herokuapp.com/

**Comment by swoogles** [comment]
Also, please let us know if you encounter any major problems when trying to execute the ScalaFix upgrade rule :)

**Comment by sandeepkota** [comment]
Sure thing. Thanks 😄

**Comment by vigoo** [comment]
Hi @sandeepkota, thank you for offering your help! 
Please note that the reason why this is not done yet is that I wanted to finish this refactor first: https://github.com/coralogix/zio-k8s/pull/289 which makes it much easier to change things involving imports. 

That said just upgrading the dependencies without doing related changes (like refactoring to the new module pattern) may not be that painful without finishing #289 first so if you want to try feel free to do so.

Also ScalaFix will not help with the generated code unfortunately.

**Comment by sandeepkota** [comment]
@vigoo 
I understand. May I know what's left on #289, I'll see if I can help in anyway.

Yes, ScalaFix is not at all helpful with codegen project, doing changes manually.
