### ISSUE TITLE
How to build this in Scala 3?

### ISSUE THREAD

**Issue by PhilAndrew** [coralogix/zio-k8s#396]
How to build this to publish scala 3 artifact locally?

**Comment by vigoo** [comment]
Both on ZIO 1 branch (`master`) and ZIO 2 branch (`zio2`):

```
sbt ++ 3.1.3 zio-k8s-client/publishLocal zio-k8s-client-quicklens/publishLocal zio-k8s-client-optics/publishLocal zio-k8s-operator/publishLocal
```
Note that `zio-k8s-monocle` subproject is not available for Scala 3 (because it depends on Monocle 2: https://github.com/coralogix/zio-k8s/issues/231), also the `zio-k8s-crd` is only available for 2.12 because it is an sbt plugin.
