### ISSUE TITLE
Watchforever starting with a resourceVersion

### ISSUE THREAD

**Issue by liafizan** [coralogix/zio-k8s#466]
We have a requirement to user `watchForever` but starting with a `resourceVersion`(optional). This would allow us to resume our watches from a specific version in the event of client reconnects and save some expensive calls to k8s api server

**Comment by vigoo** [comment]
Until it is added to the library you can already do this using `watch`, something like

```scala
ZStream.succeed(Reseted[T]()) ++
  watch(namespace, Some(resourceVersion), fieldSelector, labelSelector).catchSome {
    case Gone =>
      watch(namespace, None, fieldSelector, labelSelector).retry(Schedule.recurWhileEquals(Gone))
  }
```

(did not test it)

**Comment by liafizan** [comment]
Could you assign this to me? Working on contributing a fix for this in the coming days

**Comment by trena-dhingra** [comment]
Hi @vigoo , @liafizan and I will be working on adding resourceVersion to watchForever. Can you please assign the issue to me?
